name: firebase
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.4 <3.0.0"

dependencies:
  cloud_firestore: ^4.2.0
  cupertino_icons: ^1.0.2
  device_preview: ^1.1.0
  equatable: ^2.0.5
  firebase_auth: ^4.2.0
  firebase_core: ^2.4.0
  firebase_remote_config: ^3.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  quickalert: ^1.0.0
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: ElMessiri
      fonts:
        - asset: assets/fonts/ElMessiri-Bold.ttf
          weight: 700
        - asset: assets/fonts/ElMessiri-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/ElMessiri-Medium.ttf
          weight: 500
        - asset: assets/fonts/ElMessiri-Regular.ttf
          weight: 400
